apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    name: minecraft
spec:
  type: NodePort
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
  selector:
    app: dockerminecraft
